# Generated by Django 3.1.4 on 2023-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebody',
            name='body_img',
            field=models.ImageField(default='../static/imge/logo/blogo.jpg', upload_to='home_body'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='id_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_1',
            field=models.ImageField(default='../static/imge/slider/slider1.jpg', upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_2',
            field=models.ImageField(default='../static/imge/slider/slider2.jpg', upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_3',
            field=models.ImageField(default='../static/imge/slider/slider3.jpg', upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='title',
            field=models.CharField(blank=True, default='Default', max_length=20, null=True),
        ),
    ]
