# Generated by Django 3.1.4 on 2023-11-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20231130_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebody',
            name='body_img',
            field=models.ImageField(null=True, upload_to='home_body'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_1',
            field=models.ImageField(null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_2',
            field=models.ImageField(null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_3',
            field=models.ImageField(null=True, upload_to='slider'),
        ),
    ]
