# Generated by Django 3.1.4 on 2023-11-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20231130_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagebody',
            old_name='body_text',
            new_name='body_text1',
        ),
        migrations.RenameField(
            model_name='homepagebody',
            old_name='title',
            new_name='title1',
        ),
        migrations.RemoveField(
            model_name='homepagebody',
            name='body_img',
        ),
        migrations.AddField(
            model_name='homepagebody',
            name='body_img1',
            field=models.ImageField(blank=True, null=True, upload_to='home_body'),
        ),
        migrations.AddField(
            model_name='homepagebody',
            name='body_img2',
            field=models.ImageField(blank=True, null=True, upload_to='home_body'),
        ),
        migrations.AddField(
            model_name='homepagebody',
            name='body_img3',
            field=models.ImageField(blank=True, null=True, upload_to='home_body'),
        ),
        migrations.AddField(
            model_name='homepagebody',
            name='body_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagebody',
            name='body_text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagebody',
            name='title2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepagebody',
            name='title3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_1',
            field=models.ImageField(blank=True, null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_2',
            field=models.ImageField(blank=True, null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_3',
            field=models.ImageField(blank=True, null=True, upload_to='slider'),
        ),
    ]
