# Generated by Django 2.2.8 on 2023-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
