# Generated by Django 2.2.8 on 2023-12-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_number', models.IntegerField(blank=True, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
    ]
