# Generated by Django 3.1.4 on 2023-11-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20231129_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlogo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
